### ISSUE TITLE
Add util class JsonSerialization

### ISSUE THREAD

**Issue by tczhaodachuan** [typischmann/retail-crm#20]
This util class could be used at all projects when developer are developing data, needs to do a quick serialization and deserialization. Which is useful when you want to understand the data structure, and want to view the real data.

**Comment by typischmann** [comment]
Util is a good idea. One small tip:  thinking or designing it also compatible to spring . 
Another hand, with the jersey web services, the returned values could also be automatically formatted in JSON.

**Comment by tczhaodachuan** [comment]
I would just start from a simple util package, I would put the util class there, most of them are static. Without pretty printing, the json string is still unreadable.

**Comment by typischmann** [comment]
I have merged your Util class. It works good on my laptop. But can you change the third-party library from GSON to Jackson? Because I have used Jackson Annotation for some JPA entities and the Web service framework Jersey is also based on Jackson.

**Comment by typischmann** [comment]
I changed the mildestone of this Isssue from "analysis" to "development"

**Comment by tczhaodachuan** [comment]
I did a research on jackson library management, it seems they don't pack them as one jar, so in order to use it, you need to manage multiple jars, I would rather don't spent time on jackson, just use gson instead.

**Comment by typischmann** [comment]
Now we have the util class, then i  closed this issue
