### ISSUE TITLE
Consistency of Configuration, Format, Convention, etc....

### ISSUE THREAD

**Issue by typischmann** [typischmann/retail-crm#24]
We could meet different problems due to the different configurations in our computer. So I opened this issue to discuss and record what problems we have met and how to solve them.

**Comment by typischmann** [comment]
One Solved Problem: Date format  we used in sql files should always be "yyyy-mm-dd"
One Problem: In our local database we have defined different username and password for own usage. It leads to that we need rewrite the spring configuration again after we update the changes from another. How to solve it?

**Comment by tczhaodachuan** [comment]
This issue happened in my current team as well. What we do is by using a template file, property files to control the configuration. 
Or we should use same account and password across the project.

发自我的 iPhone

**Comment by typischmann** [comment]
For a temporary solution we are going to have a property file as workaround. Will you take this task? I will open a new issue for this task and assign to you.

In future:
1. Goal: After the first release we must reinstall our database to have a same username and password.
1. Goal: we should also records any changes of our configuration(it is a long-term goal. Now, it is not the first priority ).

**Comment by typischmann** [comment]
I think we have solved this problem technically. Close
