### ISSUE TITLE
A template for properties/configuration

### ISSUE THREAD

**Issue by typischmann** [typischmann/retail-crm#25]
You should also document the following in Readme or in Gist
1. Which configurations and properties should be stored in this template
2. design the format of the template
3. How to import this template file
4. How to synchronize the changes of this template between us

**Comment by typischmann** [comment]
I think it is implenmented in service module. Webservice module still needs that.

**Comment by tczhaodachuan** [comment]
Yes, I would add it.

**Comment by tczhaodachuan** [comment]
Added into webservices test folder, leave the WebContent one as the production configuration files.
