### ISSUE TITLE
Add Authentication Service such as Encrption

### ISSUE THREAD

**Issue by typischmann** [typischmann/retail-crm#42]

**Comment by typischmann** [comment]
The encryption could be implemented by triggers. The authentication is implemented as a function/stored procedure which can be called by JPA.

Postgres Encryption 
http://www.postgresql.org/docs/9.3/static/pgcrypto.html

Calling stored procedure(naitve sql) by JPA
http://www.oracle.com/technetwork/articles/vasiliev-jpql-087123.html

**Comment by typischmann** [comment]
Add pgcrypto to database. Test the new sql script

**Comment by typischmann** [comment]
http://www.jonsamwell.com/url-route-authorization-and-security-in-angular/

**Comment by tczhaodachuan** [comment]
Where do we want to store the password and username? Do we want to store them into DB?

**Comment by tczhaodachuan** [comment]
All the angularjs routing authentications requires an authenticate from server side.

**Comment by typischmann** [comment]
we need to encrypt and store the password in DB, because we don't want to provide a extra public key infrastructure

**Comment by tczhaodachuan** [comment]
https://medium.com/opinionated-angularjs/techniques-for-authentication-in-angularjs-applications-7bbf0346acec
http://demos.angularcode.com/angularcode-authentication-app/#/
Follow these tutorials
