### ISSUE TITLE
Adding .gitignore file into the repo

### ISSUE THREAD

**Issue by tczhaodachuan** [typischmann/retail-crm#8]
Testing commits for tchzhaodachuan

**Comment by typischmann** [comment]
the .gitignore should be deleted as well as .classpath and .project files of eclipse

**Comment by typischmann** [comment]
I have deleted it in my branch. Don't forget to delete it from your branch. This file should not pushed to Github repository

**Comment by typischmann** [comment]
Sorry, I didn't see that you also deleted it. Okay, I closed this issue
